# WaaC Physical and Logical Configuration with Tags and Filters
version: '1.1'

# -----------------------------------------------------
# CONFIGURAZIONE FISICA SCAFFALATURE
# Definizione fisica con sistema di tagging
# -----------------------------------------------------
physical_layout:
  warehouse_id: 'WH001'
  buildings:
    building_1:
      name: 'Main Building'
      areas:
        area_A:
          name: 'Area A'
          tags: ['ground_floor', 'forklift_accessible', 'temperature_controlled']
          racks:
            rack_A1:
              type: 'selective_pallet_rack'
              physical_properties:
                length: 30000  # mm
                height: 8000   # mm
                depth: 1100    # mm
              structure:
                bays: 10
                levels: 4
                positions_per_bay: 3
              tags:
                - location: 'front_area'
                - access: 'easy_reach'
                - height: 'medium'
                - equipment: ['forklift', 'pallet_jack']
                - storage_type: ['euro_pallet', 'industrial_pallet']
                - environment: ['dry', 'clean']
                - temperature_range: [-5, 25]  # Celsius
              
            rack_A2:
              type: 'drive_in_rack'
              # ... [physical properties come before]
              tags:
                - location: 'back_area'
                - access: 'specialized'
                - height: 'high'
                - equipment: ['reach_truck']
                - storage_type: ['euro_pallet']
                - environment: ['dry', 'dust_sensitive']
                - minimum_batch: 'full_lane'

# -----------------------------------------------------
# DEFINIZIONE DEI TAG
# Catalogo centralizzato dei tag disponibili
# -----------------------------------------------------
tag_catalog:
  location:
    values: ['front_area', 'back_area', 'mezzanine', 'ground_floor']
    type: 'single'  # può avere un solo valore
    
  access:
    values: ['easy_reach', 'specialized', 'restricted']
    type: 'single'
    
  height:
    values: ['low', 'medium', 'high']
    type: 'single'
    
  equipment:
    values: ['forklift', 'reach_truck', 'pallet_jack', 'order_picker']
    type: 'multiple'  # può avere più valori
    
  storage_type:
    values: ['euro_pallet', 'industrial_pallet', 'small_parts', 'bulk']
    type: 'multiple'
    
  environment:
    values: ['dry', 'humid', 'clean', 'dust_sensitive']
    type: 'multiple'

# -----------------------------------------------------
# CONFIGURAZIONE TENANT CON FILTRI
# -----------------------------------------------------
tenants:
  ecommerce_client:
    name: 'FastFashion SpA'
    type: 'e-commerce'
    logical_layout:
      zones:
        fast_moving:
          description: 'Zona alta rotazione'
          storage_filters:
            location:
              include: ['front_area']
              exclude: ['restricted']
            access:
              include: ['easy_reach']
            equipment:
              include: ['forklift', 'pallet_jack']
            custom_rules:
              - type: 'distance'
                max_distance_from_shipping: 50  # metri
              - type: 'height'
                max_picking_height: 1800  # mm
          
          dynamic_allocation:
            enabled: true
            expansion_rules:
              - condition: 'occupancy > 85%'
                action: 'expand_to_similar_locations'
                filters:
                  - match_tags: ['access', 'equipment']
                  - prefer_tags: ['front_area']
        
        bulk_storage:
          description: 'Stoccaggio scorte'
          storage_filters:
            storage_type:
              include: ['euro_pallet']
            environment:
              include: ['dry']
              exclude: ['dust_sensitive']
            custom_rules:
              - type: 'batch_size'
                min_batch: 10  # pallet
                
  b2b_distribution:
    name: 'IndustrialPro Srl'
    logical_layout:
      zones:
        heavy_items:
          description: 'Articoli pesanti'
          storage_filters:
            equipment:
              include: ['reach_truck']
            height:
              include: ['high']
            custom_rules:
              - type: 'weight'
                min_capacity: 1000  # kg
              - type: 'access'
                require_equipment: ['reach_truck']

# -----------------------------------------------------
# REGOLE DI FILTRO
# -----------------------------------------------------
filter_rules:
  standard_filters:
    - type: 'tag_match'
      description: 'Filtra per tag esatti'
    - type: 'tag_partial'
      description: 'Filtra per tag parziali'
    - type: 'numeric_range'
      description: 'Filtra per intervalli numerici'
      
  custom_filters:
    - type: 'distance_based'
      parameters: ['reference_point', 'max_distance']
    - type: 'capacity_based'
      parameters: ['min_capacity', 'max_capacity']
    - type: 'equipment_based'
      parameters: ['required_equipment', 'optional_equipment']

# -----------------------------------------------------
# REGOLE DI VALIDAZIONE FILTRI
# -----------------------------------------------------
filter_validation_rules:
  - rule: 'tag_consistency'
    checks:
      - valid_tag_values
      - tag_compatibility
      - required_tags_present
    
  - rule: 'filter_logic'
    checks:
      - no_contradicting_filters
      - filter_coverage
      - filter_efficiency