warehouse:
  id: 'MI001'
  name: 'Hub Milano'
  type: 'distribution_center'
  address:
    street: 'Via dell'Industria 123'
    city: 'Milano'
    postal_code: '20138'
    country: 'IT'
  
  layout:
    total_area: 12000  # m²
    areas:
      receiving:
        type: !include_common layouts/area_types.yaml#receiving
        customizations:
          doors: 5
          staging_capacity: 200  # pallet
      
      storage:
        type: !include_common layouts/area_types.yaml#storage
        racks:
          - type: !include_common layouts/rack_types.yaml#selective_pallet
            quantity: 10
            customizations:
              levels: 4
              positions_per_bay: 3
