integration:
  type: 'erp'
  provider: 'sap'
  connection:
    type: 'api'
    base_url: '${SAP_API_URL}'
    auth:
      type: 'oauth2'
      client_id: '${SAP_CLIENT_ID}'
      client_secret: '${SAP_CLIENT_SECRET}'
  
  mappings:
    items:
      - source: 'Material'
        target: 'item'
        fields:
          - source: 'MaterialNumber'
            target: 'sku'
          - source: 'Description'
            target: 'description'
    
    orders:
      - source: 'PurchaseOrder'
        target: 'inbound_order'
        fields:
          - source: 'PONumber'
            target: 'order_id'
