version: '1.0'
name: 'waac-configuration'
description: 'Configurazione WaaC multi-tenant'

# Importazione delle configurazioni comuni
imports:
  common:
    layouts: !include_dir_merge_list common/layouts
    processes: !include_dir_merge_list common/processes
    master_data: !include_dir_merge_list common/master_data

# Importazione dei tenant
tenants: !include_dir_merge_list tenants
