# Standard item attributes configuration
attributes:
  - id: 'dimensions'
    name: 'Physical Dimensions'
    type: 'object'
    properties:
      length:
        type: 'number'
        unit: 'mm'
      width:
        type: 'number'
        unit: 'mm'
      height:
        type: 'number'
        unit: 'mm'
    required: true

  - id: 'weight'
    name: 'Weight'
    type: 'number'
    unit: 'kg'
    required: true

  - id: 'storage_requirements'
    name: 'Storage Requirements'
    type: 'object'
    properties:
      temperature_range:
        type: 'object'
        properties:
          min:
            type: 'number'
            unit: '°C'
          max:
            type: 'number'
            unit: '°C'
      humidity_range:
        type: 'object'
        properties:
          min:
            type: 'number'
            unit: '%'
          max:
            type: 'number'
            unit: '%'
    required: false
